modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="kazahana"
version="0.0.2-test"
displayName="Kazahana Mod"
credits="Created by Nor <parz> using MCreator - https://mcreator.net/about | Licence: https://raw.githubusercontent.com/Milkeyyy/kazahana/master/LICENSE"
displayURL="(JP): http://bit.ly/nor-parz_kazahanamod-ws | Wiki(JP): https://github.com/Milkeyyy/kazahana/wiki"
updateJSONURL="https://raw.githubusercontent.com/Milkeyyy/kazahana/master/update.json"
logoFile="logo.png"
authors="Milkeyyy, Sirokane"
description='''
Kazahana Mod adds new winter-themed dimensions and items to the world of Minecraft.
'''

[[dependencies.kazahana]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




