modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="kazahana"
version="0.0.2-test"
displayName="Kazahana Mod"
credits="Created by Nor <parz> using MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Milkeyyy, Sirokane"
description='''
Kazahana Mod adds new winter-themed dimensions and items to the world of Minecraft.
'''

[[dependencies.kazahana]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




